[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; We now use the local patched version in lib/MPU9250
; lib_deps =
;     bolderflight/Bolder Flight Systems MPU9250 @ ^1.0.2

[env:sender]
build_src_filter = +<sender.cpp>

[env:receiver]
build_src_filter = +<receiver.cpp>
lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.5

[env:receiver_sim]
build_src_filter = +<receiver_simulation.cpp>
lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.5